config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'flash#index'
  resources :users
  resources :categories do
    resources :transactions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :fullname, presence: true
  validates :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  AUTHENTICATE_USER_EXCEPT_CONTROLLERS = ['flash'].freeze
  before_action :configure_sign_up_params, if: :devise_controller?

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
  end

  def authenticate_user!
    return if AUTHENTICATE_USER_EXCEPT_CONTROLLERS.include?(params[:controller])

    super
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
    # @usercat = User.find(53)
    # @categories = @usercat.categories
    # @category_check = true
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/flash_controller.rb
class FlashController < ApplicationController
  def index
    return unless current_user

    redirect_to categories_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(_resourse)
    categories_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]
  before_action :set_cat

  # GET /transactions or /transactions.json
  def index
    @transactions = @setcat.transactions
    @sum_of_col = Transaction.where(category_id: @setcat.id).sum(:amount)
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.category_id = params[:category_id]
    @transaction.icon = @setcat.icon

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to category_transactions_path(@setcat), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to category_transactions_path(@setcat), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_cat
    @setcat = Category.find(params[:category_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  def sample; end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create; end

  # PATCH/PUT /users/1 or /users/1.json
  def update; end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:fullname, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flash_helper.rb
module FlashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">    
    <%= link_to category_transactions_path(category) do %>
      <span class="icon-wrapper"><%= category.icon %></span>
      <span class="name-wrapper"><%= category.name %></span>
    <% end %>
    <% @sum_of_col = Transaction.where(category_id: category.id).sum(:amount) %>
    <h3 class="amount-class"><span>¥</span><%= @sum_of_col %></h3>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: 'save-newcat') do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>   
    <%= form.select :icon, [['🚘'], ['🛒'], ['🍎'], ['📆'], ['📌']],
                  { include_blank: "Choose icon" },
                  { required: true, class: "form-select" }  %>
  </div>

  <div class="catnewtitle">
    <%= form.text_field :name, placeholder: 'Category title ' %>
  </div>

  <div class="new-cat">
    <div class="w-rectangle">
      <%= form.submit 'Save', class: "new" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div id="categories">
  <% if @categories.length > 0 %>
    <div class="content-wrapper">
      <% @categories.each do |category| %>
        <div class="cat-wrapper">
          <%= render category %>        
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="empty-body">
      <div id="typed-strings">
        <p> Keep transactions categorized. </p>
        <p> Add category. </p>
      </div>
      <span id="typed"></span>
    </div>
  <% end %>
  <div class="main new-cat"><div class="w-rectangle"><%= link_to "Add category", new_category_path %></div></div>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

<br>

app/views/categories/show.html.erb
<h2>show</h2>
<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/flash/index.html.erb
<div class="flash-page">  
  <h1><span>MY BUDGET</span></h1>   
  <div class="wrapper">
    <div><%= link_to 'LOG IN', new_user_session_path %></div>
    <div><%= link_to 'SIGN UP', new_user_registration_path %></div>     
  </div>
</div>  

app/views/layouts/_nav.html.erb
<% url = request.original_fullpath %>
  <% if url.length != 1 %>
  <nav>
    <div class="nav">  
      <a href="/" class="back"><%= image_tag("left.png") %></a>
      <% if url.include? "password" %>    
        <h5><%= 'FORGOT?' %></h5>  
      <% elsif url.include? "sign_up" %>   
        <h5><%= 'REGISTER' %></h5>
      <% elsif url.include? "sign_in" %>    
        <h5><%= 'LOGIN' %></h5>
      <% elsif url.include? "transactions" %>    
        <h5><%= 'TRANSACTIONS' %></h5>
      <% else %>
        <h5><%= url.split('/')[1].upcase %> </h5>  
      <% end %> 
      
      <% if user_signed_in? %>
        <div class="btn">
          <%= button_to "LOG OUT", destroy_user_session_path, method: :delete, data: { turbo: false } %>
        </div>
      <% elsif url.include? "sign_in" %> 
         <h6 id="nav-btn">Log in</h6>
      <% else %>
        <h6 id="nav-btn">Next</h6>
      <% end %>  
    </div> 
  </nav>
<% end %>

app/views/layouts/_notifications.html.erb
<div class="notice-wrapper">
  <% if notice %>
  <span class="note" style="color: green"><%= notice %></span>
  <% end %>
  <% if alert %>
    <span class="note" style="color: red"><%= alert %></span>
  <% end %>
     
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetUpdated</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.cdnfonts.com/css/proxima-nova-2" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>    
    
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/nav' %>
      <%= render 'layouts/notifications' %>
      <%= yield %>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.10/typed.js" integrity="sha512-tQQXRDB2wEmuJGtFrmmoFYzNTq8StA1XJrfO0OQbbTxd9G0CwaTDL6/C1y805IlvBVrMwOqob1kf6r/2U5XXVg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, :url => {action: :create}, class: 'save-newcat') do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="catnewtitle">
    <%= form.text_field :name, placeholder: "Title", required: true %>
  </div>

  <div class="catnewtitle">
    <%= form.number_field :amount, placeholder: 'Mount', required: true %>
  </div>

  <div class="new-cat">
    <div class="w-rectangle">
      <%= form.submit 'Save', class: "new" %>
    </div>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">    
    <span>
      <span class="icon-wrapper"><%= transaction.icon %></span>
      <span class="name-wrapper"><%= transaction.name %></span>
    </span>
    <h3 class="amount-class"><span>¥</span><%= transaction.amount %></h3>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
</div>

app/views/transactions/index.html.erb
<% if @transactions.length > 0 %>
  <div class="sumwrap">
    <h3 class="main"><%= 'Total' %></h3>
    <h3 class="main"><span>&#165;&nbsp;</span><%= @sum_of_col %></h3>
  </div>
<% end %>
<div id="transactions">
  <% if @transactions.length > 0 %>
    <div class="content-wrapper">
      <% @transactions.each do |transaction| %>
        <div class="cat-wrapper">
          <%= render transaction %>    
        </div>
      <% end %>
    </div>
  <% else %>
  <div class="empty-body">
      <div id="typed-strings">
        <p> Add transactions. </p>
        <p> AND </p>
        <p> Keep transactions organized. </p>        
      </div>
      <span id="typed"></span>
    </div>    
  <% end %>
  <div class="main new-cat">
    <div class="w-rectangle">
      <%= link_to "Add transaction", new_category_transaction_url %>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<%= render "form", transaction: @transaction %>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fullname, style: "display: block" %>
    <%= form.text_field :fullname %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Fullname:</strong>
    <%= user.fullname %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users,index</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>
<h2><% if user_signed_in? %>
          <%= button_to "LOG OUT", destroy_user_session_path, method: :delete, data: { turbo: false } %>
        <% end %></h2>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/sample.html.erb
<h2>SAMPLE<% if user_signed_in? %>
  <%= button_to "LOG OUT", destroy_user_session_path, method: :delete, data: { turbo: false } %>
<% end %></h2>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<h2>show</h2>
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>